export const ROUTES = {
  home: "/",
  vehicles: "/vehicles",
  vehicleDetail: (id: number | string) => `/vehicles/${id}`,
  vehicleDetailPattern: "/vehicles/:id",
  housing: "/housing",
  propertyDetail: (id: number | string) => `/housing/${id}`,
  propertyDetailPattern: "/housing/:id",
  bookings: "/bookings",
  chat: "/chat",
  notifications: "/notifications",
  profile: "/profile",
  settings: "/settings",
  admin: "/admin",
  adminVehicles: "/admin/vehicles",
  adminVehicleCategories: "/admin/vehicle-categories",
  adminProperties: "/admin/properties",
  adminBookings: "/admin/bookings",
  adminReviews: "/admin/reviews",
  adminUsers: "/admin/users",
  adminNotifications: "/admin/notifications",
  adminAnalytics: "/admin/analytics",
} as const;
